@extends('layouts/web/web')

@section('styles')
<style type="text/css">
   .profile-header{
      height: 200px;
   }
     body
   {
   	font-size: 1rem;
   }
</style>
@endsection

@section('content')

<div class="Grid-cell u-lg-size4of5 container mt-5 mb-5">
   <div class="Panel Panel--lg">
      <div class="u-mb2">
         <div class="Grid">
            <div class="Grid-cell u-lg-before1of8 u-lg-size6of8 u-lg-after1of8">
               <div>
                  <div>
                     <h1>Terms of Service</h1>
                  </div>
                  <hr>
               </div>
               <span>
                  <p>Last Updated: August 22, 2018</p>
                  <p>Skiski Terms of Service</p>
                  <p>PLEASE READ THESE TERMS OF SERVICE CAREFULLY.</p>
                  <p>You agree that by clicking “join-now”, participating in the Referral Program (defined below), registering, accessing, or using our Services (described below), you are agreeing to enter into a legally binding contract with Collaborative Jet Skiing, Inc. operating as d/b/a Skiski, (hereafter referred to as “Skiski”, “we”, “us”, or “our”). &nbsp;If you do not agree that these Terms of Service (“Terms”) form a contract with you, or should you not wish to agree to these Terms, do not click “join-now” and do not access or otherwise use any of the Services. If you do not agree to these Terms, you have no right to obtain information from or otherwise continue using the Services. Failure to use the Services in accordance with these Terms may subject you to civil and / or criminal penalties</p>
                  <p>You agree to comply with and be legally bound by these Terms, whether or not you become a registered user of the Services. These Terms govern your access to and use of the Services and all Collective Content (defined below), and your participation in the Referral Program (defined below). &nbsp;These Terms constitute a binding legal agreement between you and Skiski.</p>
                  <p>Skiski provides an online platform that connects Owners who have Jet Skis (as defined below) to rent with Renters seeking to rent such Jet Skis, which platform is accessible at <a target="_blank" href="https://skiski.ca/">http://www.Skiski.com</a> and any other websites through which Skiski makes the platform available (collectively, the “Site") with any other websites, applications, features, software or services provided, owned, or operated by Skiski that link to these Terms are, collectively, the “Services”.</p>
                  <p>Your use of our Services is also subject to our <a target="_blank" href="">Privacy Policy</a>. Other services offered by Skiski may be subject to separate terms.</p>
                  <p>YOU UNDERSTAND AND AGREE THAT Skiski IS NOT A PARTY TO ANY AGREEMENTS ENTERED INTO BETWEEN OWNERS AND RENTERS, NOR IS Skiski A Jet Ski BROKER, AGENT OR INSURER. Skiski HAS NO CONTROL OVER THE CONDUCT OF OWNERS, RENTERS AND OTHER USERS OF THE SITE, APPLICATION AND SERVICES OR ANY Jet SkiS, AND DISCLAIMS ALL LIABILITY IN THIS REGARD.</p>
                  <p>When using or opening an account with Skiski on behalf of a company, entity, or organization, you represent and warrant that you: (i) are an authorized representative of that entity with the authority to bind that organization to these Terms and grant the licenses set forth; and (ii) agree to these Terms on behalf of such entity.</p>
                  <h6><b>Definitions</b></h6>
                  <p>“BareJet Ski Rental” A rental of a Jet Ski supported by a written agreement whereby the Jet Ski Owner transfers “the incidents of ownership” including but not limited to full possession, control and use of the Jet Ski to Renter and Renter is responsible for all aspects of the Jet Ski during the Rental including manning, provisioning and otherwise.</p>
                  <p>“Jet Ski(s)” means marine vessels.</p>
                  <p>“Skiski Content” means all Content that Skiski makes available through the Services, including any Content licensed from a third party, but excluding Member Content.</p>
                  <p>“Collective Content” means Member Content and Skiski Content.</p>
                  <p>“Content” means text, graphics, images, music, software, audio, video, information and any other content or materials.</p>
                  <p>“Renter” means a Member who requests a booking of a Jet Ski via the Services, or a Member who uses a Jet Ski and is not the Owner for such Jet Ski.</p>
                  <p>“Owner” means a person who creates and manages a Listing via the Services, is responsible for approving rentals, checking in or out a Renter, or responding to messages on the website. The Owner does not have to be the Jet Ski Jet Ski Owner, but will need to be appointed and approved by the Jet Ski Owner.</p>
                  <p>“Listing” means a Jet Ski that is listed by an Owner as available for rental via the Services.</p>
                  <p>“Member” means a person who completes Skiski's account registration&nbsp;process, including, but not limited to Owners and Renters</p>
                  <p>“Member Content” means all Content that a Member posts, uploads, publishes, submits or transmits to be made available through the Services.</p>
                  <p>“Service Fee Policy” The list of fees associated with transactions that are available via the Services. &nbsp;A list of the current charges and fees can be found by visiting the Service Fee Policy: <a target="_blank" href="">https://www.Skiski.com/legal/fee_policy</a>.<br></p>
                  <p>“Time Charter” A rental of a Jet Ski supported by a written agreement whereby the Jet Ski Owner makes the Jet Ski available to the Renter but the Owner remains responsible for all aspects of operating the Jet Ski including but not limited to manning and provisioning the Jet Ski. An Owner of a Jet Ski rented pursuant to a Time Charter must ensure compliance with all applicable coast guard, local, state and federal laws for the specific type of operation of the Jet Ski.<br></p>
                  <p>“Tax” or “Taxes” mean any sales taxes, goods and services taxes (GST), value added tax (VAT), and any other applicable or similar municipal, state and federal indirect or other withholding and personal or corporate income taxes. Certain areas of the Services (and your access to or use of certain aspects of the Services or Collective Content) may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these Terms and the terms and conditions posted for a specific area of the Services, the latter terms and conditions will take precedence with respect to your use of or access to that area of the Services.</p>
                  <h6>Modification</h6>
                  <p>Skiski reserves the right, at its sole discretion, to modify the Services or to modify these Terms, including the Service Fees (defined below), at any time and without prior notice. If we modify these Terms, we will post the modification on the Services or provide you with notice of the modification. We will also update the “Last Updated Date” at the top of these Terms. Your continued use of our Services after we publish or send a notice about our changes to these Terms means that you are consenting to the updated Terms. If the modified Terms are not acceptable to you, your only recourse is to cease using the Services.</p>
                  <h6>Minimum Age</h6>
                  <p>The Services are intended solely for persons who are 16 or older. Any access to or use of the Services by anyone under 16 is expressly prohibited. By accessing or using the Services you represent and warrant that you are 16 or older.</p>
                  <h6>How the Services Work</h6>
                  <p>The Services can be used to facilitate the listing and booking of Jet Skis. Such Jet Skis are included in Listings on the Services by Owners. You may view Listings as an unregistered visitor to the Services; however, if you wish to book a Jet Ski or create a Listing, you must first register to create a Skiski Account (defined below). As stated above, Skiski makes available a platform or marketplace with related technology for Renters and Owners to meet online and arrange for bookings of Jet Skis. Skiski is not an Owner or operator of Jet Skis, including, but not limited to, powerJet Skis, sailJet Skis, ski Jet Skis, yachts, houseJet Skis, kayaks, or other Jet Skis, nor is it a provider of Jet Skis, including, but not limited to, powerJet Skis, sailJet Skis, ski-Jet Skis, yachts, houseJet Skis, kayaks, or other Jet Skis, and Skiski does not own, sell, resell, furnish, provide, rent, re-rent, manage and/or control Jet Skis, including, but not limited to, powerJet Skis, sailJet Skis, ski Jet Skis, yachts, houseJet Skis, kayaks, or other Jet Skis, or transportation or travel services. Skiski’s responsibilities are limited to: (i) facilitating the availability of the Services and (ii) serving as the limited agent of each Owner for the sole purpose of accepting payments from Renters on behalf of the Owner.</p>
                  <p>PLEASE NOTE THAT, AS STATED ABOVE, THE SERVICES ARE INTENDED TO BE USED TO FACILITATE THE BOOKING OF Jet SkiS. Skiski CANNOT AND DOES NOT CONTROL THE CONTENT CONTAINED IN ANY LISTINGS AND/OR THE CONDITION, LEGALITY OR SUITABILITY OF ANY Jet SkiS. Skiski IS NOT RESPONSIBLE FOR AND DISCLAIMS ANY AND ALL LIABILITY RELATED TO ANY AND ALL LISTINGS AND Jet SkiS. ACCORDINGLY, ANY BOOKINGS WILL BE MADE AT THE RENTER’S AND OWNER’S OWN RISK.</p>
                  <h6>Account Registration</h6>
                  <p>In order to access certain features of the Services, and to book a Jet Ski or create a Listing, you must register to create an account (“Skiski Account”) and become a Member. You may register to join the Services directly via the Services or as described in this section.</p>
                  <p>You can also register to join by logging into online accounts you may have with third-parties, such as Facebook; each such account, a “Third Party Account”, via our Services. As part of the Services, you may link your Skiski Account with Third Party Accounts, by either: (i) providing your Third Party Account login information to Skiski through the Services; or (ii) allowing Skiski to access your Third Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third Party Account. You represent that you are entitled to disclose your Third Party Account login information to Skiski and/or grant Skiski access to your Third Party Account (including, but not limited to, for use for the purposes described herein), without breach by you of any of the terms and conditions that govern your use of the applicable Third Party Account and without obligating Skiski to pay any fees or making Skiski subject to any usage limitations imposed by such third party service providers. By granting Skiski access to any Third Party Accounts, you understand that Skiski will access, make available and store (if applicable) any Content that you have provided to and stored in your Third Party Account (“TPA Content”) so that it is available on and through the Services via your Skiski Account and Skiski Account profile page. Unless otherwise specified in these Terms, all TPA Content, if any, will be considered to be Member Content for all purposes of these Terms. Depending on the Third Party Accounts you choose and subject to the privacy settings that you have established in such Third Party Accounts, personally identifiable information that you post to your Third Party Accounts will be available on and through your Skiski Account on the Services. Please note that if a Third Party Account or associated service becomes unavailable or Skiski’s access to such Third Party Account is terminated by the third party service provider, then TPA Content will no longer be available on and through the Site, Services and Application. You have the ability to disable the connection between your Skiski Account and your Third Party Accounts, at any time, by accessing the “Account” section of the Site and Application.</p>
                  <p>PLEASE NOTE THAT YOUR RELATIONSHIP WITH THIRD PARTY SERVICE PROVIDERS ASSOCIATED WITH YOUR THIRD PARTY ACCOUNTS IS GOVERNED SOLELY BY YOUR AGREEMENT(S) WITH SUCH THIRD PARTY SERVICE PROVIDERS.</p>
                  <p>Skiski makes no effort to review any TPA Content for any purpose, including but not limited to, for accuracy, legality or non-infringement and Skiski is not responsible for any TPA Content.</p>
                  <p>We will create your Skiski Account and your Skiski Account profile page for your use of the Services based upon the personal information you provide to us or that we obtain via a Third Party Account as described above.</p>
                  <p>You may not have more than one (1) active Skiski Account. You agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete. Skiski reserves the right to suspend or terminate your Skiski Account and your access to the Services if you create more than one (1) Skiski Account or if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete.</p>
                  <p>You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your Skiski Account, whether or not you have authorized such activities or actions. You will immediately notify Skiski of any unauthorized use of your Skiski Account.</p>
                  <p>Unless expressly permitted in writing by Skiski, you may not sell, rent, or lease your Skiski Account to anyone else.</p>
                  <h6>Jet Ski Listings</h6>
                  <p>As a Member, you may create Listings. You will be asked a variety of questions about the Jet Ski to be listed, including, but not limited to, the value, location, size, features, availability of the Jet Ski, pricing, related rules, and financial terms. You acknowledge and agree that Listings will be made publicly available via the Services. Other Members will be able to book your Jet Ski via the Services based upon the information provided in your Listing. You understand and agree that once a Renter requests a booking of your Jet Ski, the price for such booking may not be altered without contacting customer service (<a target="_blank">contact@Skiski.com</a>).</p>
                  <p>You acknowledge and agree that you are responsible for any and all Listings you post. Accordingly, you represent and warrant that any Listing you post and the booking of, or Renter use of, a Jet Ski in a Listing you post (i) will not breach any agreements you have entered into with any third parties and (ii) will (a) be in compliance with all applicable laws, tax requirements, and rules and regulations that may apply to any Jet Ski included in a Listing you post, including, but not limited to, insurance requirements, coast guard regulations, zoning laws, marina regulations, and laws governing rentals and operation of Jet Skis and (b) not conflict with the rights of third parties. Please note that Skiski assumes no responsibility for an Owner’s compliance with any applicable laws, rules and regulations. Skiski reserves the right, at any time and without prior notice, but without obligation to do so, to remove or disable access to any Listing for any reason, including Listings that Skiski, in its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Services.</p>
                  <p>You understand and agree that Skiski does not act as an insurer or as a contracting agent for you as an Owner. If a Renter requests a booking of your Jet Ski and uses your Jet Ski, any agreement you enter into with such Renter is between you and the Renter and Skiski is not a party thereto. Notwithstanding the foregoing, Skiski serves as the limited authorized payment agent of the Owner for the sole purpose of accepting payments from Renters on behalf of the Owner and is responsible for transmitting such payments to the Owner.</p>
                  <p>When you create a Listing, you may also choose to include certain requirements which must be met by the Members who are eligible to request a booking of your Jet Ski, including, but not limited to, requiring Members to have a profile picture or verified phone number, in order to book your Jet Ski. Any Member wishing to book Jet Skis included in Listings with such requirements must meet these requirements; however, as noted below, we do not attempt to confirm or verify such information.</p>
                  <p>If you are an Owner, Skiski makes certain tools available to you to help you to make informed decisions about which Members you choose to confirm for booking your Jet Ski. You acknowledge and agree that, as an Owner, you are responsible for your own acts and omissions.</p>
                  <h6>No Endorsement</h6>
                  <p>Skiski does not endorse any Members or Jet Skis. Although these Terms require Members to provide accurate information, we do not attempt to confirm, and do not confirm, any Member’s purported identity or other information provided by such Member. You are responsible for determining the identity and suitability of others who you contact via the Services. Except as provided by the Skiski Terms, we will not be responsible for any damage or harm resulting from your interactions with other Members.</p>
                  <p>By using the Services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other Members or other third parties will be limited to a claim against the particular Members or other third parties who caused you harm and you agree not to attempt to impose liability on, or seek any legal remedy from Skiski with respect to such actions or omissions. Accordingly, we encourage you to communicate directly with other Members on the Services regarding any bookings or Listings made by you. This limitation shall not apply to any claim by an Owner against Skiski regarding the remittance of payments received from a Renter by Skiski on behalf of an Owner, which instead shall be subject to the limitations described in the section below entitled “Limitation of Liability”.</p>
                  <h6>Bookings and Financial Terms</h6>
                  <p>If you are an Owner and a booking is requested for your Jet Ski via the Services, you may be required to either confirm or reject the booking within 24 hours of when the booking is requested (as determined by Skiski in its sole discretion) or the booking request may be automatically canceled. When a booking is requested via the Services, we will share with you (i) the first and last name of the Renter who has requested the booking, and, (ii) a link to the Renter’s Skiski Account profile page, so that you can view such information before confirming or rejecting the booking. If you are unable to confirm or decide to reject a booking of a Jet Ski within such 24 hour period, any amounts collected by Skiski for the requested booking may be refunded to the applicable Renter’s credit card and any pre-authorization of such credit card will be released. When you confirm a booking requested by a Renter, Skiski will send you an email, text message or message via the Services confirming such booking, depending on the selections you make via the Services.</p>
                  <p>If the Renter requests a booking from one of the alternative listings and the Owner associated with such alternative listing confirms the Renter’s requested booking, then the Renter agrees to pay Skiski the Total Fees relating to the confirmed booking for the Jet Ski in the alternative listing, in accordance with these Terms.</p>
                  <p>The fees displayed in each Listing are comprised of the Jet Ski Fees and the Reservation Fees. Where applicable, Taxes may be charged in addition to the Reservation Fees and Jet Ski Fees. The Jet Ski Fees, the Reservation Fees and applicable Taxes are collectively referred to in these Terms as the “Total Fees”. The amounts due and payable by a Renter solely relating to an Owner’s Jet Ski which are actually collected by Skiski are the Jet Ski Fees. Please note that it is the Owner, and not Skiski which determines the Jet Ski Fees. The Jet Ski Fees may include cleaning fees and / or pre-paid fuel charges, at the Owner’s discretion. &nbsp;</p>
                  <p>The Renter is liable for all fuel expenses during the term of a BareJet Ski Rental. &nbsp;To the extent that an Owner seeks reimbursement for fuel expenses incurred by the Renter directly from the Renter, a receipt must be presented. &nbsp;Without a receipt the Owner will be unable to obtain reimbursement. This is true if the reimbursement is processed through Skiski or directly between the Renter and Owner. &nbsp;Following presentation of the receipt Skiski may first attempt to collect from the deposit or may charge the Renter’s card if the deposit is no longer on file.</p>
                  <p>Skiski charges a fee to Renters based upon a percentage of the Jet Ski Fees; this charge is referred to as the “Reservation Fees”. The Reservation Fee is added to the Jet Ski Fees to calculate the Total Fees (which will also include applicable Taxes) displayed in the applicable Listing. Skiski will collect the Total Fees at the time of booking confirmation (i.e. when the Owner confirms the booking within 24 hours of the booking request) and will initiate payment of the Jet Ski Fees (less Skiski’s Service Fees as defined in the Fees Policy <a target="_blank" href="">http://Skiski.co/fees</a>) to the Owner two business days provided Skiski has the accurate account information after the Renter arrives at the applicable Jet Ski (except to the extent that a refund is due to the Renter).</p>
                  <p>Failure to charge any of the fees or other indulgences shall not constitute a waiver of the right to exercise the same in the event another fee should become due at any other time.</p>
                  <p>Should a Renter not respond to an inquiry (such as regarding a fuel expense), Skiski may accept and process charges for damages, late fees, or fuel on behalf of that Renter. &nbsp;If an Owner does not respond, Skiski may process refunds or cancellations on behalf of that Owner.</p>
                  <p>You also agree that if Skiski is unable to collect a debt that is due within 30 (thirty) days, it may resort to a third party recovery service for the amount owed. In the event a third party recovery service is used, you agree that Skiski may pursue an action against you for the original amount owed, plus any commissions or expenses (including attorneys’ fees) related to pursuing said amount.</p>
                  <h6>Agreed Exclusivity with Skiski</h6>
                  <p>As an Owner, you agree to use the Service to communicate and facilitate a rental with a Renter. You agree not to take any action directly or indirectly to circumvent the Service Fee Policy. If you do so, you agree that Skiski may charge you a fee up to $1,000 per booking, in addition to the Service Fees otherwise owed to Skiski. &nbsp;Skiski may collect the fee from future bookings or otherwise.</p>
                  <p><b><br></b></p>
                  <h6>Minimum Age to Rent</h6>
                  <p>The minimum age to rent varies by type of rental &nbsp;(BareJet Ski operated by Renter, BareJet Ski operated by a Captain hired by Renter, Time Charter (Owner operated)). For all Jet Skis that are not covered under the Peer-to-Peer Jet Ski Rental Insurance Policy through Geico (ie. have their own policy), the minimum age to rent a Jet Ski is 18. For BareJet Ski rentals operated by Renter and insured through the policy made available via the Services during the rental, the minimum age is 25 and each Renter must pass a Renter verification. For BareJet Ski Rentals that are operated by licensed captains hired by Renter that are insured through the policy made available via the Services during the rental, the minimum age is 18.</p>
                  <h6>Insurance</h6>
                  <p>It is the Renter’s responsibility to &nbsp;review the insurance for their rental. Please review any insurance policy carefully, and in particular please make sure that you are familiar with and understand any exclusions to, and any deductibles that may apply for, such insurance policy, including, but not limited to, whether or not your insurance policy will cover the actions or inactions of, or relating to Renters or any hired Captains (and the individuals the Renter invites to the rental, if applicable) while on the Jet Ski. &nbsp;If the Owner is using the Peer-to-Peer Jet Ski Rental Insurance Policy through Geico it can be reviewed &nbsp;<a target="_blank" href="">here</a>, please send any questions to <a target="_blank">Skiskiunderwriting@Jet SkiUS.com</a> or call 877-510-2628.</p>
                  <h6>Appointment of Skiski as Limited Payment Agent for Owner</h6>
                  <p>Each Owner hereby appoints Skiski as the Owner's limited agent solely for the purpose of collecting payments made by Renters on behalf of the Owner. Each Owner agrees that payment of Jet Ski Fees made by a Renter to Skiski shall be considered the same as a payment made directly to the Owner and the Owner will make the Jet Ski available to Renter in the agreed upon manner as if the Owner has received the Jet Ski Fees. Each Owner agrees that Skiski may, in accordance with the cancellation policy selected by the Owner and reflected in the relevant Listing, (i) permit the Renter to cancel the booking and (ii) refund to the Renter that portion of the Jet Ski Fees specified in the applicable cancellation policy. In accepting appointment as the limited authorized payment agent of the Owner, Skiski assumes no liability for any acts or omissions of the Owner.</p>
                  <p>From time to time, we may become aware of users attempting to conduct a transaction that would involve an unauthorized payment method or a fraudulent payment method. &nbsp;Ideally, we hope to be able to assist users in avoiding such transactions, but we assume no liability or responsibility to either do so or to inform users of any such actual or suspected activity.</p>
                  <p>You are immediately responsible to Skiski for all credit card disputes, refunds, reversals, or fines regardless of the reason or timing. In many but not all cases, you may have the ability to challenge such actions by submitting evidence to <a target="_blank">contact@Skiski.com</a>. We may request additional information to provide to Financial Services Providers to assist you in contesting the charge, but we cannot guarantee that your challenge will be successful. Financial Services Providers may deny your challenge for any reason they deem appropriate. Where a challenge is entirely or partially successful, a Financial Services Provider may credit funds associated with the charge that is the subject of the dispute (or a portion thereof).</p>
                  <p><b><br></b></p>
                  <p>Please keep in mind that you are liable for all losses you incur when lost or stolen payment credentials or accounts are used to purchase products or services from you. Skiski does not and will not insure you against losses caused by fraud under any circumstances. For example, if someone pretends to be a legitimate Renter but is a fraudster, you will be responsible for any resulting costs, including credit card disputes, even if the Rental has been rendered. Even if we work with you to assist you or law enforcement in recovering lost funds, Skiski is not liable to you, or responsible for your financial losses or any other consequences of such fraud.</p>
                  <p><b><br></b></p>
                  <h6>No Charge for Listings</h6>
                  <p>Please note that Skiski does not currently charge fees for the creation of Listings. However, you acknowledge and agree that Skiski reserves the right, in its sole discretion, to charge you for and collect fees from you for the creation of Listings, or for other features of the Services. Please note that Skiski will provide notice of any such additional fees via the Services, prior to implementing such fees.</p>
                  <h6>Bookings and Financial Terms for Renters</h6>
                  <p>The Owners, not Skiski, are solely responsible for honoring any confirmed bookings and making available any Jet Skis reserved through the Services. If you, as a Renter, choose to enter into a transaction with an Owner for the booking of a Jet Ski, you agree and understand that you will be required to enter into an agreement with the Owner and you agree to accept any terms, conditions, rules and restrictions associated with such Jet Ski imposed by the Owner. You acknowledge and agree that you, and not Skiski, will be responsible for performing the obligations of any such agreements, that Skiski is not a party to such agreements, and that, with the exception of its obligations hereunder to pay Jet Ski Fees to the applicable Owner, Skiski disclaims all liability arising from or related to any such agreements. You acknowledge and agree that, notwithstanding the fact that Skiski is not a party to the agreement between you and the Owner, Skiski acts as the Owner’s limited payment agent for the limited purpose of accepting payments from you on behalf of the Owner. Upon your payment of amounts to Skiski which are due to the Owner, your payment obligation to the Owner for such amounts is extinguished, and Skiski is responsible for remitting such amounts, less Skiski’s Reservation Fees, to the Owner. In the event that Skiski does not remit any such amounts to an Owner, such Owner will have recourse for such amounts only against Skiski.</p>
                  <p>Listings for Jet Skis will specify the Total Fees. As noted above, the Owner is required to either confirm or reject the booking within 24 hours of when the booking is requested (as determined by Skiski in its sole discretion) or the requested booking may be automatically canceled. If a requested booking is canceled (i.e. not confirmed by the applicable Owner), any amounts collected by Skiski will be refunded to such Renter, depending on the selections the Renter makes via the Services, and any pre-authorization of such Renter’s credit card will be released, if applicable.</p>
                  <p>You agree to pay Skiski for the Total Fees for any booking requested in connection with your Skiski Account if such requested bookings are confirmed by the applicable Owner. In order to establish a booking pending the applicable Owner’s confirmation of your requested booking, you understand and agree that Skiski, on behalf of the Owner, reserves the right, in its sole discretion, to (i) obtain a pre-authorization via your credit card for the Total Fees or (ii) charge your credit card a nominal amount, not to exceed one dollar ($1) to verify your credit card. Once Skiski receives confirmation of your booking from the applicable Owner, Skiski will collect the Total Fees in accordance with these Terms and the pricing terms set forth in the applicable Listing. Please note that Skiski cannot control any fees that may be charged to a Renter by his or her bank related to Skiski's collection of the Total Fees, and Skiski disclaims all liability in this regard.</p>
                  <p>In connection with your requested booking, you will be asked to provide billing information such as name, billing address and credit card information either to Skiski or its third party payment processor. You agree to pay Skiski for any confirmed bookings made in connection with your Skiski Account in accordance with these Terms by one of the methods described on the Service – e.g. by PayPal or credit card. You hereby authorize the collection of such amounts by charging the credit card provided as part of requesting the booking, either directly by Skiski or indirectly, via a third party online payment processor or by one of the payment methods described on the Services. You also authorize Skiski to charge your credit card in the event of damage caused on a Jet Ski as contemplated under “Damage to Jet Skis” below and for Security Deposits, if applicable. If you are directed to Skiski’s third party payment processor, you may be subject to terms and conditions governing use of that third party's service and that third party's personal information collection practices. Please review such terms and conditions and privacy policy before using the services. Once your confirmed booking transaction is complete you will receive a confirmation email summarizing your confirmed booking.</p>
                  <h6>Payment Processing Errors and Chargebacks</h6>
                  <p>We will take steps to rectify any payment processing errors that we become aware of. These steps may include crediting or debiting (as appropriate) the same payment method used for the original payout to or payment by you, so that you end up receiving or paying the correct amount.</p>
                  <p>If an Owner is paid for a trip erroneously or a chargeback takes place, Skiski will first attempt to debit the funds from the provided bank account. &nbsp;If Skiski is unable to debit the funds to the Renter, the Owner is responsible for returning those funds within seven (7) days. Skiski may collect all future payouts until the erroneous payment or chargebacks have been resolved.</p>
                  <h6>Payment Processor Terms (Stripe)</h6>
                  <p>Payment processing services on Skiski are provided by Stripe and are subject to the <a target="_blank" href="">Stripe Connected Account Agreement</a>, which includes the <a target="_blank" href="">Stripe Terms of Service</a> (collectively, the “Stripe Services Agreement”). You agree to be bound by the Stripe Services Agreement. You also authorize Skiski to share with Stripe transaction information related to your use of the payment processing services provided by Stripe.</p>
                  <h6>Security Deposits</h6>
                  <p>Skiski includes a security deposit&nbsp;in every Listing (“Security Deposits”). For all Security Deposits included in a Listing for a confirmed booking of a Jet Ski, Skiski will, in its capacity as the payment agent of the Owner, use its commercially reasonable efforts to obtain a pre-authorization of the Renter’s credit card in the amount the Owner determines for the Security Deposit within a reasonable time prior to the Renter's check-in at the applicable Owner’s Jet Ski. Skiski will also use its commercially reasonable efforts to address Owners’ requests and claims related to Security Deposits, but Skiski is not responsible for administering or accepting any claims by Owners related to Security Deposits, and disclaims any and all liability in this regard.</p>
                  <p>If an Owner does not respond to the questions related to a Security Deposit capture within 7 days of the rental date, the damages will be considered resolved. &nbsp;As a result, the Renter’s Security Deposit will be refunded and the Owner will no longer have any rights to the funds.</p>
                  <p>Renters are always responsible for having a card on file with sufficient funds available to cover the Security Deposit and any applicable deductible. &nbsp;Skiski reserves the right to cancel the booking if the Security Deposit was not captured within 24 hours of the rental. If a booking has concluded and the Security Deposit was not captured, Skiski reserves the right to charge any/all payment methods in order to secure the necessary funds.</p>
                  <h6>Service Fees</h6>
                  <p>In consideration for providing the Services, Skiski collects service fees from Owners and Renters. Service Fees are made up of two (2) components: (i) Reservation Fee and (ii) an Owner Commission Fee that is charged to the Owner, each is based upon a percentage of the amount of the Jet Ski Fees. Where applicable, Taxes may also be charged. Owner Commission Fees are deducted from the Jet Ski Fees before remitting the Jet Ski Fees to the Owner. Reservation Fees are, as noted above, included in the Total Fees.</p>
                  <p>The agreed upon Owner payout amount will be remitted by Skiski to Owners via direct deposit or other payment methods described on the Services, in U.S. dollars. More information on Services Fees can be found at <a target="_blank" href="">http://www.Skiski.com/fees</a>. Except as otherwise provided herein, Service Fees are non-refundable.</p>
                  <h6>Referral Program</h6>
                  <p>As a Member, by referring your friends to request a booking or create a Listing that receives a confirmed booking via the Site, you may participate in the “Referral Program”, which is a loyalty program we offer to our Members. If you choose to participate in the Referral Program, for each friend you refer to Skiski for which a Qualifying Referral (defined below) is completed, you may be able to receive Skiski Jet Skiing Credits. “Skiski Jet Skiing Credits” are “reward points” that may be applied as credits toward future confirmed bookings made by Members via the Services.</p>
                  <p>In order to receive a Referral Reward, defined to mean an award of a certain amount of Skiski Jet Skiing Credits based on a Qualifying Referral(s), each of the following requirements must be satisfied (collectively, a “Qualifying Referral”): (i) you must log in to your Skiski Account on the Site and select either the “Invite Friends on Facebook” or “Invite Friends on Twitter” link; (ii) you must share the link provided with friends, by copying and pasting the unique referral link generated via the Services, by sending the unique referral link generated via the Services in an email via the Services to your friends; or by using the other tools provided by Skiski to share the unique referral link with friends; (iii) a friend who clicks the link on Facebook or otherwise or clicks the link contained in the email must create a Skiski Account and become a Member; and (iv) after becoming a Member, the friend must either request a booking of a Jet Ski which is confirmed by the applicable Owner or create a Listing which subsequently receives a confirmed booking via the Services with Total Fees of at least two hundred dollars ($200) that is not subsequently cancelled. Please note that you may not be the Owner or the Renter for the booking to receive a Referral Reward.</p>
                  <p>Upon satisfaction of a Qualifying Referral, you will receive a Referral Reward that will be reflected in your Skiski Account in a reasonable amount of time after the Qualifying Referral has been completed. The Referral Rewards you accrue will be displayed in your Skiski Account page. Referral Rewards can be accrued solely by you and you may not earn Referral Rewards by permitting another individual to use your Skiski Account. Referral Rewards accrued in multiple Skiski Accounts may not be combined into one Skiski Account. You may not earn Referral Rewards by creating multiple Skiski Accounts. By acquiring Referral Rewards, you agree and acknowledge that Skiski is granting you a limited, revocable license to a digital item, and that Referral Rewards are not your personal property. You may not obtain any cash or money in exchange for Referral Rewards. Except as explicitly provided herein, Referral Rewards are non-transferable. Members are responsible for keeping track of the Referral Rewards in their Skiski Accounts.</p>
                  <h6>Specific Terms Regarding Skiski Jet Skiing Credits</h6>
                  <p>Skiski Jet Skiing Credits may only be redeemed for confirmed bookings via the Site and after you accrue Skiski Jet Skiing Credits, such Skiski Jet Skiing Credits will be automatically applied to your next confirmed booking made via the Site. You may only redeem Skiski Jet Skiing Credits after the Skiski Jet Skiing Credits are reflected in your Skiski Account. The scope, variety, and type of services and products that you may obtain by redeeming Skiski Jet Skiing Credits can change at any time.</p>
                  <p>Skiski Jet Skiing Credits expire one (1) year from the date that any Skiski Jet Skiing Credits are last accrued in your Skiski Account. Skiski will notify you at the email address you provided during Account registration within thirty (30) days of when the Skiski Jet Skiing Credits in your Skiski Account are scheduled to expire. If for some reason you believe that there is a discrepancy regarding your balance of Skiski Jet Skiing Credits, please contact us via a <a target="_blank" href="">support ticket</a>. Skiski may require to you to submit additional information in order to make a determination regarding your balance. All decisions regarding your balance will be final and at Skiski's sole discretion. You are responsible for any Tax consequences, if any, that may result from your redemption or use of Skiski Booking Credits.</p>
                  <p>Without limiting any other terms of these Terms and subject to applicable law, all Skiski Jet Skiing Credits are forfeited if your Skiski Account is terminated or suspended for any reason, in Skiski’s sole discretion, or if Skiski discontinues providing the Service or the Referral Program.</p>
                  <h6>Limited Time Only</h6>
                  <p>This incentive program is for a limited time only. The requirements and incentives are subject to change. We reserve the right to suspend your Skiski Account and remove referrals should we notice any activity we determine as abuse of the referral program.</p>
                  <h6>Captains</h6>
                  <p>BareJet Ski Rentals: &nbsp;Where a Renter elects to hire a captain to meet the minimum manning requirements for a Jet Ski during a BareJet Ski Rental the following applies:</p>
                  <ol>
                     <li>
                        <p>Renter is free to select any captain who &nbsp;meets the minimum manning qualifications established by the Owner for the rental. &nbsp;This includes any captain made available through the Services or any captain not listed on the site that the Renter chooses, subject to confirmation and qualification of that captain by underwriters.</p>
                     </li>
                     <li>
                        <p>Jet Ski Captain Service Agreement. The hiring of a captain by a Renter is subject</p>
                     </li>
                  </ol>
                  <p>to the terms and conditions of the Jet Ski Captain Service Agreement between the Renter and the Renter’s chosen captain.</p>
                  <ol>
                     <li>
                        <p>No Endorsement. In order to promote safety and a great experience Skiski may provide a list of available captains whom have been preapproved by underwriters and which may be available to be hired by the Renter whether required by the Owner or requested by the Renter. Skiski CANNOT AND DOES NOT CONTROL THE CONTENT CONTAINED IN ANY LISTINGS OR OFFERINGS BY CAPTAINS NOR THE CONDITION, LEGALITY, SUITABILITY, INSURABILITY OR QUALIFICATIONS OF ANY CAPTAINS. Skiski never approves or endorses any captain. Skiski requires captains to submit evidence of their qualifications at the time of initial sign up but does not and is not responsible to ensure that a captain’s credentials remain current at the time of any particular Rental. Ensuring that a captain is currently credentialed and properly qualified for a particular Jet Ski or rental is the sole responsibility of the Renter.</p>
                     </li>
                     <li>
                        <p>Captains Are Strictly Retained by Renter. Renter agrees that it alone will be the employer of any captain selected and / or hired by Renter and that said captain will be so notified by Renter and agree that they are not the employee or borrowed servant of the Owner or Skiski and will make no claims of any kind against Owner or Skiski on the basis of any alleged employment relationship</p>
                     </li>
                     <li>
                        <p>Renter is solely responsible for obtaining / confirming the proper insurance coverage for any paid operator /Captain hired by the Renter.</p>
                     </li>
                     <li>
                        <p>Captain’s Fee. Captains are responsible to set the net amount they wish to charge for their Services. Renter’s are responsible for payment of the captain’s fee. &nbsp;In the event of a Rental being canceled by Owner the policy as set forth in the Jet Ski Captain Service Agreement will control.</p>
                     </li>
                  </ol>
                  <h6>General Booking and Financial Terms</h6>
                  <h6>Damage to Jet Skis - BareJet Ski Rentals</h6>
                  <p>As a Renter, you are responsible for leaving the Jet Ski in the condition it was in &nbsp;at delivery, fair wear and tear excepted. You acknowledge and agree that, as a Renter, you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals who you invite to, or otherwise provide access to the Jet Ski. In the event that following the conclusion of a rental, a Jet Ski Owner claims &nbsp;that the Jet Ski has been damaged during the rental and provides evidence of damage, including but not limited to, photographs, or other evidence you agree to pay the cost of repairing the damage or replacing the damaged items with equivalent items. After being notified of the claim and given forty eight (48) hours to respond, the payment will be charged to and taken from the credit card on file in your Skiski Account. Skiski also reserves the right to charge the credit card on file in your Skiski Account, or otherwise collect payment from you and pursue any avenues available to Skiski in this regard, including using Security Deposits, in situations in which you have been determined, in Skiski’s sole discretion, to have damaged the Jet Ski, including, but not limited to, in relation to any payment requests made by Jet Ski Owner, and in relation to any payments made by Skiski to Jet Ski Owners. If we are unable to charge the credit card on file or otherwise collect payment from you, you agree to remit payment for any damage to the Jet Ski to the applicable Jet Ski Owner or to Skiski (if applicable).</p>
                  <p>Both Renter and Jet Ski Owner agree to cooperate with and assist Skiski in good faith, and to provide Skiski with such information and take such actions as may be reasonably requested by Skiski, in connection with any complaints or claims made by Members relating to Jet Skis or any personal or other property located at a Jet Ski or with respect to any investigation undertaken by Skiski or a representative of Skiski regarding use or abuse of the Site, Application or the Services. If you are a Renter, upon Skiski's reasonable request, and to the extent you are reasonably able to do so, you agree to participate in mediation or similar resolution process with a Jet Ski Owner, at no cost to you, which process will be conducted by Skiski or a third party selected by Skiski, with respect to losses for which the Jet Ski Owner is requesting payment from Skiski under these terms. &nbsp;When an insurance claim is filed the Renter’s Security Deposit will be captured and if applicable used to cover the insurance deductible.</p>
                  <h6>Cancellations and Refunds</h6>
                  <p>If, as a Renter, you cancel your requested booking before the requested booking is confirmed by an Owner, Skiski will cancel any pre-authorization to your credit card and/or refund any nominal amounts charged to your credit card in connection with the requested booking within a commercially reasonable time. If, as a Renter, you wish to cancel a confirmed booking made via the Services, either prior to or after arriving at the Jet Ski, the cancellation policy of the Owner contained in the applicable Listing will apply to such cancellation. Our ability to refund the Jet Ski Fees and other amounts charged to you will depend upon the terms of the applicable cancellation policy. Details regarding refunds and cancellation policies are available via the Services.</p>
                  <p>If an Owner cancels a confirmed booking made via the Services, (i) Skiski will refund the Total Fees for such booking to the applicable Renter within a commercially reasonable time of the cancellation and (ii) the Renter may receive an email or other communication from Skiski containing alternative available Listings and other related information. If the Renter requests a booking from one of the alternative Listings and the Owner associated with such alternative Listing confirms the Renter’s requested booking, then the Renter agrees to pay Skiski the Total Fees relating to the confirmed booking for the Jet Ski in the alternative Listing, in accordance with these Terms. If an Owner cancels a confirmed booking and you, as a Renter, have not received an email or other communication from Skiski, please contact our support team via a <a target="_blank" href="">support ticket</a>.</p>
                  <h6>Taxes</h6>
                  <p>IRS regulation, regarding federal tax reporting requirements, stipulates that Skiski must collect IRS Form W-9 from all Owners in the United States. You understand and agree that you are solely responsible for determining your applicable Tax reporting requirements in consultation with your tax advisors. Skiski cannot and does not offer Tax-related advice to any Members of the Site, Application and Services. Additionally, please note that each Owner is responsible for determining local indirect Taxes and for including any applicable Taxes to be collected or obligations relating to applicable Taxes in Listings. Where applicable, or based upon request from an Owner, Skiski may issue a valid VAT invoice to such Owner.</p>
                  <p>Depending on your account status, forms submitted to Skiski, and other factors, you may receive a Tax form from Skiski. &nbsp;As always, we encourage you to consult a tax professional for assistance reporting your income. Skiski expects to issue Tax forms as follows::</p>
                  <p>1099 K Requirements - The Internal Revenue Service (IRS) requires that all US companies operating as a third party settlement organization (TPSO) report any information concerning third network transactions of any participating payee only if, for the calendar year:</p>
                  <ul>
                     <li>
                        <p>The gross amount of total reportable payment transactions exceeds $20,000, AND</p>
                     </li>
                  </ul>
                  <ul>
                     <li>
                        <p>The total number of such transactions exceeds 200.</p>
                     </li>
                  </ul>
                  <p>If a business makes payments via a third party settlement organization as well as cash or check to the same independent contractor, the TPSO will be required to report the amount of reportable transactions that exceed the de minimis thresholds on Form 1099-K. &nbsp;If you cross both IRS thresholds in a calendar year, Skiski will provide you with a Form 1099-K.</p>
                  <p>Keep in mind that Skiski cannot and does not offer tax-related advice to any members on the site. Additionally, please note that each Owner is responsible for determining local indirect taxes and for including any applicable taxes to be collected or obligations relating to applicable taxes in listings. You can read more on taxes by clicking on the link to the IRS page that better explains the <a target="_blank" href="">Sharing Economy Tax</a>.</p>
                  <h6>User Conduct</h6>
                  <p>You understand and agree that you are solely responsible for compliance with any and all laws, rules, regulations, and Tax obligations that may apply to your use of the Services and Content. In connection with your use of our Services, you may not and you agree that you will not:</p>
                  <ul>
                     <li>
                        <p>violate any local, state, provincial, national, maritime or other law or regulation, or any order of a court, including, without limitation, zoning restrictions, admiralty law and Tax regulations;</p>
                     </li>
                     <li>
                        <p>use manual or automated software, devices, scripts, robots, other means or processes to access, scrape, crawl or spider any web pages or other services contained in the Services or Content;</p>
                     </li>
                     <li>
                        <p>use the Services for any commercial or other purposes that are not expressly permitted by these Terms;</p>
                     </li>
                     <li>
                        <p>Falsely imply that Skiski endorses you, is a partner, or otherwise misleads others as to your affiliation with Skiski;</p>
                     </li>
                     <li>
                        <p>copy, store or otherwise access any information contained on the Services or Content for purposes not expressly permitted by these Terms;</p>
                     </li>
                     <li>
                        <p>Use Jet Ski ramps where you have not been authorized to operate.</p>
                     </li>
                     <li>
                        <p>infringe the rights of any person or entity, including without limitation, their intellectual property, privacy, publicity or contractual rights;</p>
                     </li>
                     <li>
                        <p>interfere with or damage our Services, including, without limitation, through the use of viruses, cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, packet or IP spoofing, forged routing or electronic mail address information or similar methods or technology;</p>
                     </li>
                     <li>
                        <p>use our Services to transmit, distribute, post or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information or credit, debit, calling card or account numbers;</p>
                     </li>
                     <li>
                        <p>use our Services in connection with the distribution of unsolicited commercial email (“spam”) or advertisements unrelated to the rental of Jet Skis;</p>
                     </li>
                     <li>
                        <p>stalk or harass any other user of our Services or collect or store any personally identifiable information about any other user other than for purposes of transacting as a Skiski Renter or Owner;</p>
                     </li>
                     <li>
                        <p>offer, as an Owner, any Jet Skis that you do not yourself own or have permission to rent</p>
                     </li>
                     <li>
                        <p>offer, as an Owner, any Jet Ski that may not be rented pursuant to the terms and conditions of an agreement with a third party;</p>
                     </li>
                     <li>
                        <p>register for more than one Skiski Account or register for a Skiski Account on behalf of an individual other than yourself;</p>
                     </li>
                     <li>
                        <p>contact an Owner for any purpose other than asking a question related to a booking such Owner's Jet Skis or Listings;</p>
                     </li>
                     <li>
                        <p>contact a Renter for any purpose other than asking a question related to a booking or such Renter's use of the Site, Application and Services;</p>
                     </li>
                     <li>
                        <p>when acting as a Renter or otherwise, recruit or otherwise solicit any Owner or other Member to join third party services or websites that are competitive to Skiski, without Skiski’s prior written approval;</p>
                     </li>
                     <li>
                        <p>impersonate any person or entity, or falsify or otherwise misrepresent yourself or your affiliation with any person or entity;</p>
                     </li>
                     <li>
                        <p>use automated scripts to collect information or otherwise interact with the Services;</p>
                     </li>
                     <li>
                        <p>use the Services to find an Owner or Renter and then complete a booking of a Jet Ski transaction independent of the Services in order to circumvent the obligation to pay any Service Fees related to Skiski’s provision of the Services;</p>
                     </li>
                     <li>
                        <p>as an Owner, submit any Listing with a false or misleading price information, or submit any Listing with a price that you do not intend to honor;</p>
                     </li>
                     <li>
                        <p>post, upload, publish, submit or transmit any Content that, in Skiski’s sole judgment: (i) infringes, misappropriates or violates a third party's patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil or criminal liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any other person; or (vii) promotes illegal or harmful activities or substances;</p>
                     </li>
                     <li>
                        <p>systematically retrieve data or other content from our Services to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots, crawlers, or spiders, or otherwise;</p>
                     </li>
                     <li>
                        <p>use, display, mirror or frame the Services, or any individual element within the Services, Skiski’s name, any Skiski trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without Skiski’s express written consent;</p>
                     </li>
                     <li>
                        <p>access, tamper with, or use non-public areas of the Services, Skiski’s computer systems, or the technical delivery systems of Skiski’s providers;</p>
                     </li>
                     <li>
                        <p>attempt to probe, scan, or test the vulnerability of any Skiski system or network or breach any security or authentication measures;</p>
                     </li>
                     <li>
                        <p>avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by Skiski or any of Skiski’s providers or any other third party (including another user) to protect the Services or Collective Content;</p>
                     </li>
                     <li>
                        <p>forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services or Collective Content to send altered, deceptive or false source-identifying information;</p>
                     </li>
                     <li>
                        <p>attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Services or Collective Content; or</p>
                     </li>
                     <li>
                        <p>advocate, encourage, or assist any third party in doing any of the foregoing.</p>
                     </li>
                  </ul>
                  <p>Skiski will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. Skiski may involve and cooperate with law enforcement authorities in prosecuting users who violate these Terms. You acknowledge that Skiski has no obligation to monitor your access to or use of the Services or Collective Content or to review or edit any Member Content, but has the right to do so for the purpose of operating the Services, to ensure your compliance with these Terms, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. Skiski reserves the right, at any time and without prior notice, to remove or disable access to any Collective Content that Skiski, at its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Services.</p>
                  <h6>Privacy</h6>
                  <p>See Skiski’s Privacy Policy at <a target="_blank" href="">http://www.Skiski.co/privacy</a> for information and notices concerning Skiski’s collection and use of your personal information.</p>
                  <h6>Ownership</h6>
                  <p>The Services are owned and operated by Skiski. Unless otherwise indicated, all content, information, and other materials on the Services (excluding Member Content), including, without limitation, Skiski’s trademarks and logos, the visual interfaces, graphics, design, compilation, information, software, computer code (including source code or object code), services, text, pictures, information, data, sound files, other files and the selection and arrangement thereof (collectively, the “Materials”) are protected by relevant intellectual property and proprietary rights and laws. All Materials contained on the Services are the property of Skiski or its subsidiaries or affiliated companies and/or third-party licensors. Unless otherwise expressly stated in writing by Skiski, by agreeing to these Terms you are granted a limited, non-sublicensable license (i.e. a personal and limited right) to access and use the Services solely for your personal use or business use as identified in these Terms. &nbsp;Skiski can terminate this license at any time, without notice.</p>
                  <p>No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Skiski or its licensors, except for the licenses and rights expressly granted in these Terms.</p>
                  <h6>Member Content, License to Skiski</h6>
                  <p>Unless otherwise agreed to in a written agreement between you and Skiski that was signed by an authorized representative of Skiski, if you submit, transmit, display, perform, post or store Member Content using the Services, you grant Skiski and its sublicensees an unrestricted, worldwide, perpetual, irrevocable, fully sub-licenseable, nonexclusive, and royalty-free right to (a) use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such Member Content (including without limitation for promoting and redistributing part or all of the Services (and derivative works thereof)) in any form, format, media or media channels now known or later developed or discovered; and (b) use the name, identity, likeness and voice (or other biographical information) that you submit in connection with such Member Content.</p>
                  <p>Member Content Representations</p>
                  <p>You are solely responsible for your Member Content and the consequences of posting or publishing it. By uploading and publishing your Member Content, you represent, and warrant that: (1) you are the creator and owner of the Member Content or otherwise have sufficient rights and authority to grant the rights granted herein; (2) your Member Content does not and will not (a) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right or (b) defame any other person; and (3) your Member Content does not contain any viruses, adware, spyware, worms, or other harmful or malicious code. Skiski reserves all rights and remedies against any Members who breach these representations and warranties.</p>
                  <h6>Links</h6>
                  <p>The Services may contain links to third-party websites or resources. You acknowledge and agree that Skiski is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Skiski of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources or the Content, products or services on or available from such websites or resources.</p>
                  <h6>Proprietary Rights Notices</h6>
                  <p>All trademarks, service marks, logos, trade names and any other proprietary designations of Skiski used herein are trademarks or registered trademarks of Skiski. Any other trademarks, service marks, logos, trade names and any other proprietary designations are the trademarks or registered trademarks of their respective parties.</p>
                  <h6>Feedback</h6>
                  <p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Services (“Feedback”). You may submit Feedback through our support portal via a <a target="_blank" href="">support ticket</a>. You acknowledge and agree that all Feedback will be the sole and exclusive property of Skiski and you assign to Skiski all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent, copyright, trade secret, moral and other proprietary or intellectual property rights therein. At Skiski's request and expense, you will execute documents and take such further acts as Skiski may reasonably request to assist Skiski to acquire, perfect, and maintain its intellectual property rights and other legal protections for the Feedback.</p>
                  <h6>Copyright Dispute Policy</h6>
                  <p>Skiski respects copyright law and expects its users to do the same. &nbsp;If you are a copyright owner or agent thereof and believe that content posted on the Skiski Services infringes upon your copyright, please submit a notice following our <a target="_blank" href="">Policy</a>, which include further information about what to include in your notice, and where to submit your notice</p>
                  <h6>Termination and Skiski Account Cancellation</h6>
                  <p>We may, in our discretion and without liability to you, with or without cause, with or without prior notice and at any time: (a) terminate these Terms or your access to our Services, and (b) deactivate or cancel your Skiski Account. Upon termination we will promptly pay you any amounts we reasonably determine we owe you in our discretion, which we are legally obligated to pay you. In the event Skiski terminates these Terms, or your access to our Services or deactivates or cancels your Skiski Account you will remain liable for all amounts due hereunder. You may cancel your Skiski Account at any time by contacting us via a <a target="_blank" href="">support ticket</a>. Please note that if your Skiski Account is canceled, we do not have an obligation to delete or return to you any Content you have posted to the Services, including, but not limited to, any reviews or Feedback.</p>
                  <h6>Disclaimers</h6>
                  <p>IF YOU CHOOSE TO USE THE SERVICES, YOU DO SO AT YOUR SOLE RISK. YOU ACKNOWLEDGE AND AGREE THAT Skiski DOES NOT HAVE AN OBLIGATION TO CONDUCT BACKGROUND CHECKS ON ANY MEMBER, INCLUDING, BUT NOT LIMITED TO, RENTERS AND OWNERS, BUT MAY CONDUCT SUCH BACKGROUND CHECKS IN ITS SOLE DISCRETION. THE SERVICES, COLLECTIVE CONTENT ARE PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, Skiski EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. Skiski MAKES NO WARRANTY THAT THE SERVICES, COLLECTIVE CONTENT, INCLUDING, BUT NOT LIMITED TO, THE LISTINGS OR ANY Jet SkiS, WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. Skiski MAKES NO WARRANTY REGARDING THE QUALITY OF ANY LISTINGS, Jet SkiS, THE SERVICES OR COLLECTIVE CONTENT OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY COLLECTIVE CONTENT OBTAINED THROUGH THE SERVICES.</p>
                  <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM Skiski OR THROUGH THE SERVICES OR COLLECTIVE CONTENT, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
                  <p>YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SERVICES, INCLUDING, BUT NOT LIMITED TO, ANY OWNERS OR RENTERS. YOU UNDERSTAND THAT Skiski DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE SITE, APPLICATION OR SERVICES OR TO REVIEW OR INSPECT ANY Jet SkiS. Skiski MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE SITE, APPLICATION OR SERVICES OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE SITE, APPLICATION OR SERVICES. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE, APPLICATION OR SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE, APPLICATION OR SERVICES, INCLUDING, BUT NOT LIMITED TO, RENTERS AND OWNERS, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON REGARDLESS OF WHETHER SUCH MEETINGS ARE ORGANIZED BY Skiski.</p>
                  <p>YOU AUTHORIZE Skiski, DIRECTLY OR THROUGH THIRD PARTIES SUCH AS COGNITO, TO MAKE ANY INQUIRIES WE CONSIDER NECESSARY TO HELP VERIFY OR CHECK YOUR IDENTITY OR PREVENT FRAUD. THIS MAY INCLUDE ASKING YOU TO PROVIDE A FORM OF GOVERNMENT IDENTIFICATION (E.G. DRIVER’S LICENSE OR PASSPORT), YOUR DATE OF BIRTH, AND OTHER INFORMATION REQUIRING YOU TO TAKE STEPS TO CONFIRM OWNERSHIP OF YOUR EMAIL ADDRESS, PAYMENT METHODS OR PAYOUT METHODS; OR ATTEMPTING TO SCREEN YOUR INFORMATION AGAINST THIRD PARTY DATABASES. Skiski RESERVES THE RIGHT TO CLOSE, SUSPEND, OR LIMIT ACCESS TO THE PAYMENT SERVICES IN THE EVENT WE ARE UNABLE TO OBTAIN OR VERIFY ANY OF THIS INFORMATION.</p>
                  <p>NOTWITHSTANDING Skiski’S APPOINTMENT AS THE LIMITED AGENT OF THE OWNERS FOR THE PURPOSE OF ACCEPTING PAYMENTS FROM RENTERS ON BEHALF OF THE OWNERS, Skiski EXPLICITLY DISCLAIMS ALL LIABILITY FOR ANY ACT OR OMISSION OF ANY RENTER OR OTHER THIRD PARTY.</p>
                  <h6>Limitation of Liability</h6>
                  <p>YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR ACCESS TO AND USE OF THE SERVICES AND COLLECTIVE CONTENT, YOUR LISTING OR BOOKING OF AND USE OF ANY Jet SkiS VIA THE SERVICES, , AND ANY CONTACT YOU HAVE WITH OTHER USERS OF THE SERVICES WHETHER IN PERSON OR ONLINE REMAINS WITH YOU. NEITHER Skiski NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES, COLLECTIVE CONTENT WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE PRODUCTS OR SERVICES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, FROM THE USE OF OR INABILITY TO USE THE SERVICES OR COLLECTIVE CONTENT, FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF THE SERVICES OR OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SERVICES, OR FROM YOUR LISTING, BOOKING, OR USE OF ANY Jet Ski VIA THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT Skiski HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</p>
                  <p>EXCEPT FOR OUR OBLIGATIONS TO PAY AMOUNTS TO APPLICABLE OWNERS PURSUANT TO THESE TERMS, IN NO EVENT WILL Skiski'S AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS AND YOUR USE OF THE SERVICES INCLUDING, BUT NOT LIMITED TO, FROM YOUR LISTING, BOOKING OR USE OF ANY Jet Ski VIA THE SERVICES, OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, OR COLLECTIVE CONTENT AND IN CONNECTION WITH ANY Jet Ski OR INTERACTIONS WITH ANY OTHER MEMBERS, EXCEED THE AMOUNTS YOU HAVE PAID FOR BOOKINGS VIA THE SITE, APPLICATION AND SERVICES AS A GUEST IN THE TWELVE (12) MONTH PERIOD PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY, OR IF YOU ARE AN OWNER, THE AMOUNTS PAID BY Skiski TO YOU IN THE TWELVE (12) MONTH PERIOD PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY, OR ONE HUNDRED DOLLARS ($100), IF NO SUCH PAYMENTS HAVE BEEN MADE, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN Skiski AND YOU. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
                  <h6>Indemnification</h6>
                  <p>You agree to release, defend, indemnify, and hold Skiski and its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (a) your access to or use of the Services or Collective Content or your violation of these Terms; (b) your Member Content; (c) your (i) interaction with any Member, (ii) booking or use of a Jet Ski, (iii) creation of a Listing or (iv) the use, condition or rental of a Jet Ski by you, including, but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of a rental, booking or use of a Jet Ski.</p>
                  <h6>Export Control and Restricted Countries</h6>
                  <p>By using the Services, you represent and warrant that (i) neither you nor your listed Jet Ski is located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You also will not use the Services for any purpose prohibited by U.S. law, including the development, design, manufacture or production of missiles, or nuclear, chemical or biological weapons. Skiski does not permit Listings associated with certain countries due to U.S. embargo restrictions.</p>
                  <h6>Reporting Misconduct</h6>
                  <p>If you interact with another user of the Services who you feel is acting or has acted inappropriately, including but not limited to, anyone who (i) engages in offensive, violent or sexually inappropriate behavior, (ii) you suspect of stealing from you, or (iii) engages in any other disturbing conduct, you should immediately report such person to the appropriate authorities and then to Skiski by contacting us with your police station and report number via a <a target="_blank" href="">support ticket</a>.</p>
                  <h6>Entire Agreement</h6>
                  <p>These Terms constitute the entire and exclusive understanding and agreement between Skiski and you regarding the Services, Collective Content, and any bookings or Listings of Jet Skis made via the Services, and these Terms supersede and replace any and all prior oral or written understandings or agreements between Skiski and you regarding the foregoing.</p>
                  <h6>Assignment</h6>
                  <p>You may not assign or transfer these Terms, by operation of law or otherwise, without Skiski's prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, shall be void. Skiski may assign or transfer these Terms, at its sole discretion, without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
                  <h6>Notices</h6>
                  <p>Any notices or other communications permitted or required hereunder, including those regarding modifications to these Terms, will be in writing and given by Skiski (i) via email (in each case to the address that you provide) or (ii) by posting to the Services. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
                  <h6>Controlling Law and Jurisdiction</h6>
                  <p>By using the Services, you agree that the Federal Arbitration Act, applicable federal law, and the laws of the State of Florida, without regard to principles of conflict of laws, will govern these Terms and any dispute of any sort that might arise between you and Skiski.</p>
                  <p>You and we agree to submit to the personal jurisdiction of a state court located in Broward County, Fort Lauderdale, Florida &nbsp;or a United States District Court, Southern District of Florida located in Fort Lauderdale, Florida for any actions for which the parties seek injunctive or other equitable relief to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents, or other intellectual property rights, as set forth in the Dispute Resolution provision below.<br></p>
                  <h6>Dispute Resolution</h6>
                  <p>You and Skiski agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof, or to the use of the Services (collectively, “Disputes”) will be settled by binding arbitration, except that each party retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents, or other intellectual property rights. YOU ACKNOWLEDGE AND AGREE THAT YOU AND Skiski ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING. Further, unless both you and Skiski otherwise agree in writing, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void. Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of these Terms.</p>
                  <p>Arbitration Rules and Governing Law. With the exception of claims under $15,000 in value, any arbitration will be administered by the American Arbitration Association (“AAA”) in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the “AAA Rules”) then in effect, except as modified by this “Dispute Resolution" section. (The AAA Rules are available at<a target="_blank" href=""> http://www.adr.org/arb_med</a> or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this section.</p>
                  <p>You agree that any dispute, claim, or controversy under $15,000 in value arising out of or relating to these Terms, whether between you and Skiski or between you and other users, or the existence, breach, termination, enforcement, interpretation, or validity thereof, shall be settled by binding arbitration administered by Fairclaims (<a target="_blank" href="">www.FairClaims.com</a>) and not in a court of law, in accordance with FairClaims’ procedures effective at the time a claim is made. You further agree that judgement on the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof.</p>
                  <p>Arbitration Process. A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a form Demand for Arbitration at<a target="_blank" href=""> http://www.adr.org/aaa/ShowPDF?doc=ADRSTG_004175</a> and a separate form for California residents at<a target="_blank" href=""> http://adr.org/aaa/ShowPDF?doc=ADRSTG_004314</a>.) The arbitrator will be either a retired judge or an attorney licensed to practice law in the state of California and will be selected by the parties from the AAA’s roster of consumer dispute arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the Demand for Arbitration, then the AAA will appoint the arbitrator in accordance with the AAA Rules.</p>
                  <p>Arbitration Location and Procedure. Unless you and Skiski otherwise agree, the arbitration will be conducted in Fort Lauderdale, Florida, USA. Subject to the AAA Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.</p>
                  <p>Arbitrator’s Decision. The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator's decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator's award damages must be consistent with the terms of the “Limitation of Liability” section above as to the types and the amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant's individual claim. If you prevail in arbitration you will be entitled to an award of attorneys' fees and expenses, to the extent provided under applicable law. Skiski will not seek, and hereby waives all rights it may have under applicable law to recover, attorneys' fees and expenses if it prevails in arbitration.</p>
                  <p>Fees. Your responsibility to pay any AAA filing, administrative and arbitrator fees will be solely as set forth in the AAA Rules.</p>
                  <p>Claims. &nbsp;YOU AGREE THAT ANY DISPUTES ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE DISPUTE ACCRUES. &nbsp;OTHERWISE, THE DISPUTE IS PERMANENTLY BARRED.</p>
                  <p>EU Residents. &nbsp;If you are a consumer and have your habitual residence in the EU, you can elect to enjoy the protection afforded to you by mandatory provisions of the law of your country of residence. &nbsp;You may bring a claim to enforce your consumer protection rights in connection with these Terms or in the EU country in which you live. The European Commission provides for an online dispute resolution platform, which you can access here:<a target="_blank" href=""> https://ec.europa.eu/consumers/odr</a>.</p>
                  <p>Changes. Notwithstanding the provisions of the Modification section above, if Skiski changes this Dispute Resolution section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (via a<a target="_blank" href=""> support ticket</a> within 30 days of the date such change became effective, as indicated in the Last Updated Date above or in the date of Skiski’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and Skiski in accordance with the provisions of this Dispute Resolution section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</p>
                  <h6>General</h6>
                  The failure of Skiski to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Skiski. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason an arbitrator or a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.
                  <h6>Contacting Skiski</h6>
                  <p>If you have any questions about these Terms of Service, please contact Skiski Support via a <a target="_blank" href="">support ticket</a>.</p>
               </span>
            </div>
         </div>
      </div>
   </div>
</div>


@endsection